name: WebReact
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:80"
    depends_on:
      - backend
      

  backend:
    build:
      context: ./api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql://user:password@db:3306/database
       - PYTHONPATH=/app
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
